### ISSUE TITLE
README HID Keycode Table Squatter

### ISSUE THREAD

**Issue by NeoRubylith** [I0x0I/DIY-A-BLE-Keyboard#5]
It looks like the domain hosting the HID table (http://www.mindrunway.ru/IgorPlHex/USBKeyScan.pdf) expired so someone bought it up and set up a link to some sort of adult entertainment website.

I am still trying to learn about this stuff but found a possible replacement resource for this guide: https://deskthority.net/wiki/Scancode

**Comment by I0x0I** [comment]
Thank you for the information, the Readme has been updated.
